<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Sharp86</RootNamespace>
    <AssemblyName>Sharp86TextGuiDebugger</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <BaseOutputPath>../build/</BaseOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ConFrames/ConFrames/ConFrames.csproj" />
    <ProjectReference Include="../PetaJson/PetaJson_Net40.csproj" />
    <ProjectReference Include="../Sharp86DebuggerCore/Sharp86DebuggerCore.csproj" />
    <ProjectReference Include="../Sharp86/Sharp86.csproj" />
  </ItemGroup>
</Project>
