<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Win3muCore</RootNamespace>
    <AssemblyName>Win3muCore</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>8.0</LangVersion>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <BaseOutputPath>../build/</BaseOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Sharp86/PetaJson/PetaJson.csproj" />
    <ProjectReference Include="../Sharp86/Sharp86DebuggerCore/Sharp86DebuggerCore.csproj" />
    <ProjectReference Include="../Sharp86/Sharp86TextGuiDebugger/Sharp86TextGuiDebugger.csproj" />
    <ProjectReference Include="../Sharp86/Sharp86/Sharp86.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
