<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Win3mu</RootNamespace>
    <AssemblyName>Win3mu</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Prefer32Bit>false</Prefer32Bit>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <BaseOutputPath>../build/</BaseOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Win3muRuntime/Win3muRuntime.csproj" />
  </ItemGroup>
</Project>
