<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>PetaJson</RootNamespace>
    <AssemblyName>PetaJson</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Prefer32Bit>false</Prefer32Bit>
    <DefineConstants>PETAJSON_NO_DATACONTRACT;$(DefineConstants)</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="PetaJson.cs" />
    <Compile Include="Properties/AssemblyInfo.cs" />
  </ItemGroup>
</Project>
